# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='users',
        ),
    ]
