# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20170815_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='users_app',
        ),
    ]
